export const MAX_EMBED_TITLE_LENGTH = 256;
export const MAX_EMBED_DESCRIPTION_LENGTH = 4096;
export const MAX_EMBED_FIELD_NAME_LENGTH = 256;
export const MAX_EMBED_FIELD_VALUE_LENGTH = 1024;
export const MAX_WEBHOOK_CONTENT_LENGTH = 2000;
